resolver: lts-17.4
compiler: ghc-8.10.4

packages:
- .

ghc-options:
  "$locals": -funbox-strict-fields -funfolding-use-threshold=16 -fexcess-precision -optc-O3 -optc-ffast-math -O2 # -v

extra-deps:
- binary-strict-0.4.8.6@sha256:456da8c1452a18349fbb02134ba608cf7420014cb93e9c39e7e4b99de1c48a7e,2222

# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

allow-newer: true
